[project]
name = "drankspel"
version = "1.1.0"
description = "A random drinking game picker"
readme = "README.md"
authors = [
    { name = "Lars van Rhijn", email = "larsvanrhijn@gmail.com" }
]
license = "MIT"
requires-python = ">=3.14"
dependencies = [
    "dialogflow>=2.0.0",
    "django>=6.1.1",
    "django-cors-headers>=4.9.0",
    "django-oauth-toolkit>=3.4.1",
    "django-tinymce>=5.0.0",
    "djangorestframework>=3.18.1",
    "uritemplate>=4.2.0",
]

[dependency-groups]
dev = [
    "black>=26.5.1",
    "coverage>=7.16.2",
    "flake8>=7.4.1",
    "pydocstyle>=6.3.0",
]
prod = [
    "psycopg2-binary>=2.9.13",
    "uwsgi>=2.0.31",
]

[tool.black]
line-length = 119
target-version = ["py311"]
exclude = '''
/(
  migrations
  | website/drankspel/settings
)/
'''
