---

name: "Build Production Docker Image (backend)"
on:
  push:
    branches:
      - master

jobs:
  build-docker-backend:
    name: "Build Docker Backend image"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v5
      with:
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        tags: ghcr.io/kioui/drankspel-backend:${{ github.workflow_sha }}, ghcr.io/kioui/drankspel-backend:latest

  build-docker-frontend:
    name: "Build Docker Frontend image"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v5
      with:
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        tags: ghcr.io/kioui/drankspel-frontend:${{ github.workflow_sha }}, ghcr.io/kioui/drankspel-frontend:latest
